### ISSUE TITLE
Activity diagram

### ISSUE THREAD

**Issue by Zlatanius** [Zlatanius/BURGIJA#2]
1. Razliciti fontovi
2. Izmjeniti funkcionalnost upravljanje korisnickim racunima/ dodati registraciju
3. Dodati tekst za end point za biranje datuma iznamljivanja
4. Funk 5 staviti iz perspektive korinsika

**Comment by ibecir** [comment]
Kada zavrsite sa prepravkama, samo me oznacite na komentar da su ispravke gotove tako da mogu da pogledam prije iducih vjezbi

**Comment by aljubuncic** [comment]
@ibecir Ispravke su gotove
