### ISSUE TITLE
MVC Dijagram

### ISSUE THREAD

**Issue by ibecir** [Zlatanius/BURGIJA#22]
Zasto LoginController ima pristup RegisterView-u ad imamo i RegisterController. Na dosta mjesta ima relacija koje nemaju smisla. Cilj ovog dijagrama jeste da pokazete kako i odakle neki pogled prima podatke i kako komuniciraju a ne opet predstaviti isti klasni dijagram koji ste kreirali.

**Comment by aljubuncic** [comment]
@ibecir Dokumentacija/MVC Dijagram klasa.jpg

**Comment by aljubuncic** [comment]
@ibecir https://github.com/Zlatanius/BURGIJA/blob/main/Dokumentacija/MVC%20Dijagram%20klasa.jpg
