### ISSUE TITLE
Tasks, fixing frontend

### ISSUE THREAD

**Issue by jasarevicedis** [Zlatanius/BURGIJA#35]
Need to add: 
-div switch for sign up button/ already signed user
-update navbar with real icons
-fix hamburger menu and add new view
-filter box updates, remove location and time added
-split item(tool) components in partial views for putting on index view
-add path for categories
-remove time when added tag for tool

**Comment by Zlatanius** [comment]
-Change visibility of password field

**Comment by jasarevicedis** [comment]
issue fixed
