### ISSUE TITLE
Klasni dijagram

### ISSUE THREAD

**Issue by ebronja1** [Zlatanius/BURGIJA#4]
Napraviti dijagram klasa na izmjenjenoj analizi i dizajnu sistema

**Comment by aljubuncic** [comment]
[Dijagram klasa BURGIJA.vpd.pdf](https://github.com/Zlatanius/BURGIJA/blob/main/Dijagram%20klasa%20BURGIJA.vpd.pdf)

**Comment by ibecir** [comment]
Ja vidim ovo kad pokusam da otvorim ovaj file 

<img width="1184" alt="image" src="https://github.com/Zlatanius/BURGIJA/assets/15219309/2c2049a0-7bc5-444e-9933-b62b7ac9a3b1">

**Comment by MersidPi** [comment]
Probajte otvoriti folder Dokumentacija, pa onda ovaj fajl za klasni dijagram. Meni se tako otvori, a ovdje kad kliknem na Ahmedov komentar onda izbaci error.
